# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김형준 (Kim, Hyoung Jun)
title: 신용평가시스템 모델러 / 리스크 컨설턴트
email: junkim1003@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  atechlouiis
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: hyoung-jun-kim-039526148
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: '@louiboss5621'
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, 김형준이라고 합니다. 사교적인 활동가이자 매우 긍정적인 ENFP입니다. 
    
  테크와 투자 관련된 모든 컨텐츠를 즐기며, 장밋빛 미래를 상상하는 것을 좋아합니다.
  
  활발한 성격으로 평소에 팀 스포츠인 축구와 농구를 가장 좋아하지만, 최근엔 나 자신과의 싸움인 클라이밍과 수영에도 흥미를 느끼고 있습니다. 
  
  다양한 분야의 금융데이터를 탐구하여, 여러 시뮬레이션을 통해 전략을 도출해내고 실제 적용해보는 것에 큰 재미와 보람을 느낍니다.
  머신러닝 모델을 활용하여 많은 사람들이 직관적이고 쉽게 이용할 수 있는 디지털 서비스를 개발하여 가치를 전달하는 것이 최종 목표입니다.   
    
  관심가져주셔서 감사합니다. 좋은 인연으로 이어지면 좋겠습니다. 
  
  역량 
  - 프로그래밍 언어 : Python, SQL, R, SAS, Spark
  - Front-end : React, HTML, JS
  - 도구 : PowerBI, Q-GIS, ARcGIS, GeoDa, UCInet, Gephi
  - 언어 : ENGLISH (Proficient - TOEIC 990, TOEFL 109, OPIc AL)    

  자격증 
  - 한자능력검정시험2급 (2014)    
  - 워드프로세서 1급 (2013)
  
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NICE평가정보
        link: https://www.niceinfo.co.kr/
        sub_title: CSS모델러 / 리스크컨설턴트
        caption: 2019.01. - 현재
        description: | # this will include new lines to allow paragraphs
          금융상품별 신용평가시스템의 모형 / 전략 개발 및 컨설팅 역할을 하고 있습니다. 리스크 수준을 제한하며, 수익성을 극대화 할 수 있는 방법에 대해 끊임없이 고민하고 
          적용해보고 있습니다. 최근에는 새로운 마이데이터 시대에 발맞춰 새로운 대안정보 활용 전략 개발, 고객세그먼트 재정의 등 고객사의 니즈에 선제적으로 대응 및 제안하고 있습니다.             
      - layout: left
        title: 
        link: 
        sub_title: 
        caption: 
        description: | # this will include new lines to allow paragraphs    
          - 신용평가시스템(CSS) 스코어카드/ML모형 & 전략 개발 및 컨설팅, 모니터링 시스템 설계
          - 활용 모델: 로지스틱 회귀, GBM, DNN, RF, 대리자모형, two-target ML, explainable ML 등
              - 연체부도율 예측모형 개발                 
                > 2022.11. – 2023.03. (5M)  J축은행 신용대출(플랫폼) 모형 및 전략 |     
                > 2022.04. – 2022.12. (7M)  A대부 신용대출(플랫폼) 모형 및 전략 |  
                > 2021.10. - 2022.03. (6M)  N저축은행 신용대출(플랫폼) 모형 및 전략|    
                > 2021.04. - 2021.08. (5M)  P저축은행 대안신용평가 신용대출(플랫폼) 모형 및 전략|     
                > 2020.10. - 2020.11. (2M)  L사(P2P) ML대리자 모형 개발|
                > 2020.11. - 2020.12. (2M)  D저축은행 신용대출(플랫폼) |
                > 2020.05. - 2020.10. (6M)  S저축은행 자동차담보대출|     
              - 대안정보 활용 모형 개발 (직장정보, 부동산정보, 통신정보, 커머스정보 등)
                > 2021.04. - 2021.08. (5M)  P저축은행 대안신용평가 ML스코어| 
                > 2019.04. - 2019.07. (4M)  D사 휴대폰소액결제정보 신용평가스코어| 
              - 회생/파산/신용회복 부도율 예측모형 개발             
                > 2022.11. – 2023.03. (5M)  J저축은행 부실채권 회수가능성 모형|
                > 2019.09. - 2019.12. (4M)  K저축 회파복대출 모형 및 전략| 
                > 2019.08. - 2019.09. (2M)  A대부 회파복대출 모형 및 전략|  
 
          - 강사   
               > 2022.01. - 현재, 금융업권 종사자 대상 신용평가시스템(CSS) 고도화 과정 강사            
               > 2021.01. - 현재, 신입직원 SAS 코드 교육            
         
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 연세대학교
        caption: 2017년 - 2018년
        sub_title: 산업공학 석사
        link: http://isl.yonsei.ac.kr/
        description: | # this will include new lines to allow paragraphs
          문제를 새롭게 정의하고 다양한 데이터 분석기법을 통해 인사이트를 도출해내는 역량을 쌓았습니다. 
          주 관심/연구분야는 공간데이터를 활용한 공간패턴 탐색 및 이상치 탐지 / 특허데이터를 활용한 기술 가치 평가 / 스타트업데이터를 활용한 융합기술 예측 및 유망기업 발굴 입니다. 
             
      - layout: 
        title: 
        caption: 
        sub_title: 
        link: 
        description: | # this will include new lines to allow paragraphs
            - 공모전            
              - 제14회 KMAC 경영혁신 연구논문 및 사례연구 대학(원)생 공모전 [대상](http://isl.yonsei.ac.kr/index.php?mid=event&page=4&document_srl=7721) (2018.11.)
                - “Doc2vec 기반 협업 필터링과 요인분석을 활용한 인수합병 대상 스타트업 추천 시스템” (김형준, 김태산, 손소영*)
                   >2018.11. 한국경영공학회 정기학술세미나 프로그램 발표|
                   ><mark>Published in Decision support systems*</mark>|
            - 산학과제 - 효율적인 혁신을 위한 특허 경영 전략 계량분석 연구 (미래창조과학부, 중견 도약연구 2단계)            
              - "Cost–Benefit Model for Multi-Generational High-Technology Products to Compare Sequential Innovation Strategy with Quality Strategy" (김형준, 지수정, 손소영*)
                >2018.04 [춘계공동학술대회(한국경영학회, 대한산업공학회, 한국시뮬레이션학회) 구두발표](http://isl.yonsei.ac.kr/index.php?mid=event&page=5&document_srl=7352)|
                >2018.09 Asian Network for Quality 2018 학회 포스터 발표|
                ><mark>Published in PLOS ONE*</mark>|
            - 산학과제 - 국토공간정보의 빅데이터 관리, 분석 및 서비스 플랫폼 기술 개발 (국토교통과학기술진흥원)            
              - “Support Vector Data Description을 이용한 시간대별 유동인구 이상치 탐지” 기능 모듈 개발
              - “SPATIAL PATTERNS OF SOLE PROPRIETORSHIP AND CORPORATE PAYDAY LENDERS IN SEOUL, KOREA (김형준, 이보경, 손소영*)”
                 >2017.06. [대한지리학회 연례학술대회 구두발표](https://www.kgeography.or.kr/boards/notice/20312/detail/news/notice/)|
                 >2017.11. [국토연구원 – 공간연구 학술 교류 세미나 구두발표](http://isl.yonsei.ac.kr/index.php?mid=event&page=6&document_srl=7053)|
                 >2019.02. WRSA 58th annual meeting in Napa Valley |
                 ><mark>Published in The Annals of Regional Science*</mark>|
              - “누적합 관리도를 활용한 생활인구 이상치 탐색” (김형준, 손소영*)
                  >2018.11. 한국공간정보학회 2018년 공동추계학술대회 포스터 발표|
                  ><mark>Published in 품질경영학회지*</mark> |
                  >2021년 한국품질경영학회 춘계학술대회 [품질우수논문상](http://isl.yonsei.ac.kr/event/8743) |
            - 졸업논문            
              - ["Dynamic Link Prediction to Identify Emerging Business Areas based on Startup Market Convergence Data"](http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=7cdaec4d3c311351ffe0bdc3ef48d419&keyword=Dynamic%20Link%20Prediction%20to%20Identify%20Emerging%20Business%20Areas%20based%20on%20Startup%20Market%20Convergence%20Data)
            - 교육활동
               >2018.10. SAS PAR 조교추천 교육(SAS, SQL, ML소개 교육 3회)|
               >2018년도 1학기 데이터마이닝이론및응용 조교 (손소영 교수, SAS 및 R 프로그래밍 실습)|
            - 참여 프로그램
               >2018.06. [Qualcomm KOREA - Qualcomm (San Diego, CA) IT Tour 방문 프로그램](http://qcitour.co.kr/gallery/51973)|
               >2018.05. 연세대학교 공학교육혁신센터 - 차세대 핵심역량 Intellectual Property R&D (이수)|
               >2017.02. Stanford Research Institute - Introduction to Innovation Workshop (이수)|
                 
      - layout: left
        title: 연세대학교
        caption: 2011년 - 2016년
        sub_title: 정보산업공학 학사
        description: | # this will include new lines to allow paragraphs
          질풍노도의 대학 시기엔 호기심이 항상 많았고, 도전하는 것이 두렵지 않았습니다.          
          팀 구기 스포츠에 관심이 매우 많았으며, 여행 다니기를 좋아하였습니다. 
          무엇보다도 다양한 활동을 통하여, 여러 사람을 만났고 제가 좋아하는 것과 싫어하는 것에 대한 선택지를 좁혔습니다. 
          
      - layout:
        title:
        caption: 
        sub_title: 
        description: | # this will include new lines to allow paragraphs
            - 프로젝트              
              - 2016.09. - 2016.12. “Q-GIS 와 다중 회귀분석을 활용한 푸드트럭 입지 규제 개선"
                > 연세대학교 정보산업공학과 졸업작품 전시회 출품|
                > 한국품질경영학회 추계학술 포스터 발표|
              - 2015.12. - 2016.07. LG유플러스 채용전환형 얼리버드 3기
                > 2016.06. LG 영챌린져 PlayLGway 1등|
                > 2016.07. “감정동사를 활용한 영화 큐레이션 시스템” (김형준, 오지수, 박재범, 강준석, 서장원)| 
            - 봉사 활동
              >2016.07. - 2016.08. [공과대학교, 한국기아대책본부 주관 인도네시아 해외봉사](http://www.eeic.or.kr/www/center/bbs.do?type=view&bd_seq=1537)|
            - 동아리 활동
              >2015.09. - 2016.06. 상경대학 오퍼레이션학회 MSC 19기 회장|
              >2015.03. - 2015.12. 정보산업공학과 농구동아리 한울 회장|
              >2011.09. - 2012.10. 기수단 Blue Knights 활동|
            - 병역
              >2013.02. - 2014.11. 의무경찰 경리 행정병 병장 만기전역|
            - 조교
              >2012.06. - 2012.08. UCEAP, Korea (캘리포니아 대학교 교환학생 프로그램) 조교|
                  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:                          
      - layout: left
        title: Github
        link: https://github.com/atechlouiis
        sub_title: 자동매매 트레이딩 / 서비스 개발
        caption: 
        description: | # this will include new lines to allow paragraphs
          인간의 사사로운 감정을 투자에서 배제하고자 자동매매 트레이딩을 공부하며 개발한 단기매매 전략들과 재무제표 기반 스윙 전략 등의 프로젝트와            
          API 및 크롤링 등을 활용한 부동산 텔레그램 알리미 서비스 프로젝트를 진행하였습니다.           
          
      - layout: 
        title: 
        link: 
        sub_title:  
        caption: 
        description: | # this will include new lines to allow paragraphs
              - 주식 자동매매 트레이딩 전략 (대신증권 크레온 API 활용)
                > [장 개시후 갭상 종목 매매](https://github.com/atechlouiis/BeastHeart/blob/main/yasu.py)|
                > [거래량 400% 이상 폭발주 매매](https://github.com/atechlouiis/BeastHeart/blob/main/volume400.py)|
                > [DART API활용 수주공시 매매](https://github.com/atechlouiis/BeastHeart/blob/main/dart_supply.py)|
                > [이걸말아올려? 음봉긴꼬리 종목 매매](https://github.com/atechlouiis/BeastHeart/blob/main/long_tail.py)|
                
              - 재무제표 기반 스윙 전략 (Fnguide, DAUM증권 크롤링 활용)
                > PER/PBR 하단 주식 + RSI 발굴 [blog](https://blog.naver.com/junkim1003/222670639022), [git](https://github.com/atechlouiis/BeastHeart/blob/main/band_low.py)|
                
              - 서비스 개발         
                > [공공데이터 API활용 - 부동산 실거래가 알리미](https://github.com/atechlouiis/atechlouiis.github.io/blob/main/sil_apt.py) 개발중...|
                > [대법원경매사이트 크롤링 활용 -경매 낙찰가 알리미](https://github.com/atechlouiis/atechlouiis.github.io/blob/main/apt_auction.py) 개발중...|
                
              - 기타         
                > 국내 주식 주가, 거래량 크롤링 하기 [blog](https://blog.naver.com/junkim1003/222007045946)|
                
  - title: Postings # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 유튜브
        link: 'https://www.youtube.com/@louiboss5621'
        sub_title: 적립식 장기투자 시뮬레이션
        caption: 현재 미운영
        description: | # this will include new lines to allow paragraphs
          평소에 관심있었던 적립식 장기투자 시뮬레이션의 결과물을 Microsoft PowerBI Tool을 활용하여 데이터 시각화 컨텐츠를 만들었습니다.
          
      - layout: left
        title: 블로그
        link: https://blog.naver.com/junkim1003
        sub_title: 금융데이터 분석
        caption: 이따금씩
        description: | # this will include new lines to allow paragraphs
          성공적인 투자를 위하여, 주식 / 코인 / 부동산 등 분야를 가리지 않고 금융데이터 정량 분석 / 역사  등 다양한 주제로 포스팅을 하고 있습니다.
                   
      - layout: 
        title: 
        link: 
        sub_title:  
        caption: 
        description: | # this will include new lines to allow paragraphs
              - 주식 전략
                > [BitCoin은 어떤 금융자산과 비슷할까?](https://blog.naver.com/junkim1003/222004940301)|
                > [자산별 상관관계를 알아보자...1편](https://blog.naver.com/junkim1003/221984862054)|
                > [자산별 상관관계를 알아보자...2편](https://blog.naver.com/junkim1003/221986894512)|
                > [자산별 상관관계를 알아보자...2편](https://blog.naver.com/junkim1003/221986894512)|
                > [JYP랑 트와이스 신곡](https://blog.naver.com/junkim1003/222394652674)|
                > [IPO 관련주 언제 살까?](https://blog.naver.com/junkim1003/222332470287)|
                > [원자재 관련주와 괴리율](https://blog.naver.com/junkim1003/222322551249)|
                > [액면분할과 주가](https://blog.naver.com/junkim1003/222319619084)|
                > [장단기 금리차와 증시](https://blog.naver.com/junkim1003/222944105644)|
                > [꾸준함 vs 행운, 마켓타이밍 vs 장기투자](https://blog.naver.com/junkim1003/222675588437)|
                > [시장의 바닥은 어디인가?](https://blog.naver.com/junkim1003/222633298614)|
                > [사명 변경과 주가](https://blog.naver.com/junkim1003/222587414448)|
                
              - 부동산 지표          
                > [전세가율와 매매 타이밍...1편 서울](https://blog.naver.com/junkim1003/222924678626)|
                > [부동산은 왜? 언제? 우상향 할까? (feat.통화량)](https://blog.naver.com/junkim1003/221978453700)|
                > [부동산에 왜 투자해야 할까?](https://blog.naver.com/junkim1003/221977321740)|
                
              - 경제 전반          
                > [버블의 형성과 꺼짐...1편](https://blog.naver.com/junkim1003/222009297042)|
                > [버블의 형성과 꺼짐...2편](https://blog.naver.com/junkim1003/222010340286)|
                > [버블의 형성과 꺼짐...3편](https://blog.naver.com/junkim1003/222011169258)|
                > [칵테일이론과 동조현상](https://blog.naver.com/junkim1003/222802788312)|
                > [장단기 금리차와 증시](https://blog.naver.com/junkim1003/222944105644)|
                > [토토해서 돈을 벌 수 없는 이유](https://blog.naver.com/junkim1003/222950205751)|
                > [아파트 가격의 역사](https://blog.naver.com/junkim1003/222655117782)|
                
              - 아이디어노트        
                > [아이디어노트#1 아파트 최적위치 계산기](https://blog.naver.com/junkim1003/222485023182)|
                > [아이디어노트#2 포메이션과 주식전략](https://blog.naver.com/junkim1003/222492113405)|
                > [아이디어노트#3 BNPL](https://blog.naver.com/junkim1003/222547011011)|
                > [아이디어노트#4 KEDZE](https://blog.naver.com/junkim1003/222623427629)|
                > [아이디어노트#5 아파트-ETF](https://blog.naver.com/junkim1003/222655106323)|
                > [아이디어노트#6 NFT기반 회원권플랫폼](https://blog.naver.com/junkim1003/222675691095)|
         
                
          
                 
  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Kim, H. J., Jee, S. J., Sohn, S. Y., "Cost–Benefit Model for Multi-Generational High-Technology Products to Compare Sequential Innovation Strategy with Quality Strategy". PLOS ONE.16(4), e0249124, 2021](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0249124)
      - [Kim, H.J., Sohn, S. Y. "CUSUM Chart Applied to Monitoring Areal Population Mobility". 품질경영학회지, 48(2), 241-256. 2020.](https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=JAKO202020941304790&dbt=NART)
      - [Kim, H. J., Lee, B. K., & Sohn, S. Y. (2020). Comparing spatial patterns of sole proprietorship and corporate payday lenders in Seoul, Korea.
      The Annals of Regional Science,64(1), 215-236.](https://yonsei.pure.elsevier.com/en/publications/comparing-spatial-patterns-of-sole-proprietorship-and-corporate-p)
      - [Kim, H. J., San Kim, T., & Sohn, S. Y. (2020). Recommendation of startups as technology cooperation 
      candidates from the perspectives of similarity and potential: A deep learning approach.Decision support systems,130, 113229.](https://yonsei.pure.elsevier.com/en/publications/recommendation-of-startups-as-technology-cooperation-candidates-f)
         
# Footer
footer_show_references: true
# references_title: sproogen resume-theme (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
