# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김형준 (Kim, Hyoung Jun)
title: 신용평가시스템 모델러 / 리스크 컨설턴트
email: junkim1003@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  atechlouiis
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: hyoung-jun-kim-039526148
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: louiboss5621
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NICE평가정보
        link: https://www.niceinfo.co.kr/
        sub_title: CSS모델러 / 리스크컨설턴트
        caption: 2019.01 - 현재
        description: | # this will include new lines to allow paragraphs
          금융상품별 신용평가시스템의 모형 / 전략 개발 및 컨설팅하는 PMO 역할을 하고 있으며, 새로운 핀테크 시대에 발맞춰 고객사의 니즈에 선제적으로
          대응 및 제안하고 있습니다.             
      - layout: left
        title: 신용평가시스템 개발
        link: 
        sub_title: 스코어카드/ML모형 & 전략
        caption: 
        description: | # this will include new lines to allow paragraphs
              - 신용대출 상품 
                > 2019.04 - 2019.07  다날 휴대폰소액결제정보를 활용한 신용평가스코어 개발 |
                > 2020.10 - 2020.11  렌딧(P2P) ML모형 개발|
                > 2022.04 – 2022.12  아프로파이낸셜대부 CSS 개발 |
                > 2022.11 – 2023.03  JT친애저축은행 CSS 개발 |              
              - 플랫폼채널 / 연계채널 상품           
                > 2020.11 - 2020.12  동원제일저축은행 모형 개발|
                > 2021.10 - 2022.03  NH저축은행 CSS 개발|
                > 2022.04 – 2022.12  아프로파이낸셜대부 CSS 개발|
                > 2022.11 – 2023.03  JT친애저축은행 CSS 개발|               
              - 자동차담보대출 상품           
                > 2020.05 - 2020.10  스마트저축은행 CSS 개발|           
              - 회파복대출 상품           
                > 2019.08 - 2019.09  에이원캐피탈대부 CSS 개발|
                > 2019.09 - 2019.12  키움저축 CSS 개발|
              - 대안정보 활용 모형 개발 
                > 2019.04 - 2019.07  다날 휴대폰소액결제정보를 활용한 신용평가스코어 개발| 
                > 2021.04 - 2021.08  페퍼저축은행 대안신용평가 ML스코어 개발| 
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 연세대학교
        caption: 2011년 - 2016년
        sub_title: 정보산업공학 학사
        description: | # this will include new lines to allow paragraphs
          질풍노도의 대학 시기엔 다양한 경험을 쌓고,  팀워크 / 의사소통 /  호기심 탐구 / 미래고민.
            - 효율적인 혁신을 위한 특허 경영 전략 계량분석 연구 (중견 도약연구 2단계) (미래창조과학부)
              -"Cost–Benefit Model for Multi-Generational High-Technology Products to Compare Sequential Innovation Strategy with Quality Strategy"
                >2018.04 2018년 춘계공동학술대회(한국경영학회, 대한산업공학회, 한국시뮬레이션학회) 구두발표|
                >2018.09 Asian Network for Quality 2018 학회 포스터 발표|
                >Published in PLOS ONE (2021)|
            - 프로젝트
              >2016.07 - 2016.08 LG유플러스 채용전환형 얼리버드 3기|
               - LG 영챌린져 PlayLGway 1등 (2016.06)
               -“감정동사를 활용한 영화 큐레이션 시스템” (김형준, 오지수, 박재범, 강준석, 서장원)
              >2016.09 - 2016.12 “Q-GIS 와 다중 회귀분석을 활용한 푸드트럭 입지 규제 개선"|
               - 연세대학교 정보산업공학과 졸업작품 전시회 출품
               - 한국품질경영학회 추계학술 포스터 발표
            - 봉사 활동
              >2016.07 - 2016.08 공과대학교, 한국기아대책본부 주관 인도네시아 해외봉사|
            - 동아리 활동
              >2011.09 - 2012.10 기수단 Blue Knights 활동|
              >2015.03 - 2015.12 정보산업공학과 농구동아리 한울 회장|
              >2015.09 - 2016.06 상경대학 오퍼레이션학회 MSC 19기 회장|
                  
      - layout: left-top
        title: 연세대학교
        caption: 2017년 - 2018년
        sub_title: 산업공학 석사
        link: http://isl.yonsei.ac.kr/
        description: | # this will include new lines to allow paragraphs
          연세대학교 산업공학과 산업통계연구실 소속으로 공간데이터와 특허데이터, 스타트업 데이터를 활용하여 산학과제 및 연구를 진행하였습니다.  
            - 산학과제)효율적인 혁신을 위한 특허 경영 전략 계량분석 연구 (미래창조과학부, 중견 도약연구 2단계)
              -"Cost–Benefit Model for Multi-Generational High-Technology Products to Compare Sequential Innovation Strategy with Quality Strategy"
                >2018.04 2018년 춘계공동학술대회(한국경영학회, 대한산업공학회, 한국시뮬레이션학회) 구두발표|
                >2018.09 Asian Network for Quality 2018 학회 포스터 발표|
                >Published in PLOS ONE |
            - 산학과제)국토공간정보의 빅데이터 관리, 분석 및 서비스 플랫폼 기술 개발 (국토교통과학기술진흥원)            
              - “Support Vector Data Description을 이용한 시간대별 유동인구 이상치 탐지” 기능 모듈 개발
              - “ SPATIAL PATTERNS OF SOLE PROPRIETORSHIP AND CORPORATE PAYDAY LENDERS IN SEOUL, KOREA (H.J. Kim, B.K. Lee, S.Y. Sohn*)”
                 >2017.06. 대한지리학회 연례학술대회 구두발표|
                 >2017.11. 국토연구원 – 공간연구 학술 교류 세미나 구두발표|
                 >2019.02 WRSA 58th annual meeting in Napa Valley  |
                 >Published in The Annals of Regional Science|
              - “누적합 관리도를 활용한 생활인구 이상치 탐색”
                  >2018.11. 한국공간정보학회 2018년 공동추계학술대회 포스터 발표|
                  >Published in 품질경영학회지 |
                  >2021년 한국품질경영학회 춘계학술대회에서 품질우수논문상 수상|
            - 공모전)            
              - “Doc2vec 기반 협업 필터링과 요인분석을 활용한 인수합병 대상 스타트업 추천 시스템” (김형준, 김태산)
                 >2018.11. 제14회 KMAC 경영혁신 연구논문 및 사례연구 대학(원)생 공모전|
                 >2018.11. 한국경영공학회 정기학술세미나 프로그램 발표|
                 >Published in Decision support systems|
            - 활동)            
              - 교육)
                 >2018. SAS PAR 조교추천 교육(SAS, SQL, ML소개 교육 3회)|
                 >2018년도 1학기 데이터마이닝이론및실습(손소영 교수) 조교|
                 >2018.10 SAS 다변량 분석 교육 - 실습 조교|
                 >Published in Decision support systems|
              - 프로그램)
                 >2017.02 Stanford Research Institute - Introduction to Innovation Workshop (이수)|
                 >2018.05 연세대학교 공학교육혁신센터 - 차세대 핵심역량 Intellectual Property R&D (이수)|
                 >2018.06 Qualcomm KOREA - Qualcomm (San Diego, CA) IT Tour 방문 프로그램 |
                 
  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
         
  - title: Strengths
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
